AWSTemplateFormatVersion: '2010-09-09'
Description: Backend of CodingTips application
Resources:
  TipsDB:
    Properties:
      AttributeDefinitions:
      - AttributeName: Author
        AttributeType: S
      - AttributeName: Date
        AttributeType: N
      KeySchema:
      - AttributeName: Author
        KeyType: HASH
      - AttributeName: Date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Tips
    Type: AWS::DynamoDB::Table
  getTipsFunction:
    Properties:
      CodeUri: s3://coding-tips/d47d585eb5f7f9dba278c8a4383068eb
      Description: A simple backend that reads from CodingTips databasse
      Events:
        Api1:
          Properties:
            Method: GET
            Path: /tips
          Type: Api
      FunctionName: get-coding-tips
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - dynamodb:GetItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Tips
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  postTipsFunction:
    Properties:
      CodeUri: s3://coding-tips/1a7a0315c029b9d7d8ab3d03188521dc
      Description: A simple backend that writes to CodingTips database
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /tips
          Type: Api
      FunctionName: post-coding-tips
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Tips
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
