AWSTemplateFormatVersion: '2010-09-09'
Description: Backend of CodingTips application
Globals:
  Api:
    Cors:
      AllowHeaders: '''DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range'''
      AllowMethods: '''GET,POST,OPTIONS'''
      AllowOrigin: '''*'''
  Function:
    Environment:
      Variables:
        TABLE_NAME: Tips
Resources:
  CodingTipsApi:
    Properties:
      DefinitionBody:
        consumes:
        - application/json
        info:
          description: Gateway to CodingTips app
          title: CodingTipsAPI
          version: 1.0.0
        paths:
          /tips:
            get:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  headers:
                    Content-Type:
                      type: string
              x-amazon-apigateway-integration:
                httpMethod: POST
                passthroughBehavior: when_no_match
                responses:
                  default:
                    responseParameters:
                      method.response.header.Content-Type: integration.response.header.content-type
                    statusCode: 200
                type: aws
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getTipsFunction.Arn}/invocations
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                responses: {}
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${postTipsFunction.Arn}/invocations
        produces:
        - application/json
        schemes:
        - https
        swagger: '2.0'
      EndpointConfiguration: REGIONAL
      StageName: default
    Type: AWS::Serverless::Api
  CodingTipsDB:
    Properties:
      AttributeDefinitions:
      - AttributeName: Author
        AttributeType: S
      - AttributeName: Date
        AttributeType: N
      KeySchema:
      - AttributeName: Author
        KeyType: HASH
      - AttributeName: Date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Tips
    Type: AWS::DynamoDB::Table
  CodingTipsUsagePlan:
    DependsOn: CodingTipsApidefaultStage
    Properties:
      ApiStages:
      - ApiId:
          Ref: CodingTipsApi
        Stage: default
      - ApiId:
          Ref: CodingTipsApi
        Stage: Stage
      Description: CodingTips Usage Plan for a maximum 500 requests per day
      Quota:
        Limit: 500
        Period: DAY
      Throttle:
        BurstLimit: 5
        RateLimit: 5
      UsagePlanName: CodingTips_UsagePlan
    Type: AWS::ApiGateway::UsagePlan
  getTipsFunction:
    Properties:
      CodeUri: s3://coding-tips/d47d585eb5f7f9dba278c8a4383068eb
      Description: A simple backend that reads from CodingTips databasse
      Events:
        GetApi:
          Properties:
            Method: GET
            Path: /tips
            RestApiId:
              Ref: CodingTipsApi
          Type: Api
      FunctionName: get-coding-tips
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Tips
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 30
    Type: AWS::Serverless::Function
  postTipsFunction:
    Properties:
      CodeUri: s3://coding-tips/756e126cc472f25233ce27ee4257b2fe
      Description: A simple backend that writes to CodingTips database
      Events:
        PostApi:
          Properties:
            Method: POST
            Path: /tips
            RestApiId:
              Ref: CodingTipsApi
          Type: Api
      FunctionName: post-coding-tips
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/Tips
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 30
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
