AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Backend of CodingTips application
Resources:
  getTipsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: get-coding-tips
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: /Users/nivh/Training/aws/Serverless/CloudFormation/codingtips/get
      Description: A simple backend that reads from CodingTips databasse
      MemorySize: 128
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/Tips'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /tips
            Method: GET
  postTipsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: post-coding-tips
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: /Users/nivh/Training/aws/Serverless/CloudFormation/codingtips/post
      Description: A simple backend that writes to CodingTips database
      MemorySize: 128
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/Tips'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /tips
            Method: POST
  TipsDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: Author
          AttributeType: S
        - AttributeName: Date
          AttributeType: N
      KeySchema:
        - AttributeName: Author
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: Tips

